# Generated by Django 4.0.2 on 2022-02-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_kefiruser_birthday_alter_kefiruser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kefiruser',
            name='city',
        ),
        migrations.AddField(
            model_name='kefiruser',
            name='city',
            field=models.ManyToManyField(null=True, related_name='kefir_users', to='users.City'),
        ),
    ]
